# Generated by Django 3.1.4 on 2021-01-10 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateNilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasiNilai', models.FloatField(blank=True, default=0)),
                ('realisasiKPI', models.FloatField(blank=True, default=0)),
                ('KPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapot.templatekpi')),
                ('nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapot.templatenilai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
